# Generated by Django 4.1 on 2022-09-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostel", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=100)),
                ("room_no", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("housekeeping", "housekeeping"),
                            ("security", "security"),
                            ("geenral", "general"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cp.student"
                    ),
                ),
            ],
        ),
    ]
