# Generated by Django 4.1 on 2022-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0002_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hostel",
            field=models.CharField(
                choices=[
                    ("alakananda", "Alakananda"),
                    ("brahmaputra", "Brahmaputra"),
                    ("cauvery", "Cauvery"),
                    ("ganga", "Ganga"),
                    ("godaveri", "Godaveri"),
                    ("jamuna", "Jamuna"),
                    ("krishna", "Krishna"),
                    ("mahanadhi", "Mahanadhi"),
                    ("mandakini_a", "Mandakini A"),
                    ("mandhakini_b", "Mandakini B"),
                    ("narmada", "Narmada"),
                    ("pampa", "Pampa"),
                    ("saraswathi", "Saraswathi"),
                    ("sindhu", "Sindhu"),
                    ("tamiraparani", "Tamiraparani"),
                    ("tapti", "Tapti"),
                    ("bhadra", "Bhadra"),
                    ("sabarmati", "Sabarmati"),
                    ("sarayu", "Sarayu"),
                    ("sharavathi", "Sharavathi"),
                    ("tunga", "Tunga"),
                ],
                max_length=100,
            ),
        ),
    ]
