# Generated by Django 4.1 on 2022-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp", "0003_alter_student_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
